--Vinicius Sesti <vinicius.s.sesti@gmail.com>
--Project Euler: Problem 2
--Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
--1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


prob2list::[Int]->[Int]
prob2list xs 
  | last(xs)+(last.init) xs < 4000000 = prob2list (xs++[last(xs)+(last.init) xs])
  | otherwise = xs

sumEven::[Int]->Int 
sumEven xs = ((foldr (+) 0).(filter (\x -> mod x 2 == 0))) xs